# Generated by Django 4.2.4 on 2024-03-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=16, unique=True)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=4, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertable')),
            ],
        ),
    ]
