# Generated by Django 4.2.4 on 2024-03-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDetails',
            fields=[
                ('user_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=255)),
                ('phone_number', models.IntegerField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
