# Generated by Django 4.2.4 on 2024-03-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registrationdetails_remove_creditcard_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.registrationdetails'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
    ]
