# Generated by Django 4.2.4 on 2024-03-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_creditcard_user_id_alter_creditcard_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='store_name',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.registrationdetails'),
        ),
    ]
