# Generated by Django 4.2.4 on 2024-04-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_store_name_product_product_id_product_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(max_length=4),
        ),
    ]
